# vim:set ft=dockerfile:
FROM       centos:6

# Build fails:
#docker build -t eudat-pyhandle:py2.6 -f Dockerfile-python2.6 .
# TODO FIXME Fix this, or remove if unfixable (after all, it's py 2.6...)

RUN        yum -y update && yum clean all && yum -y install \
           python-setuptools
RUN 	   yum -y install wget
RUN 	   wget https://bootstrap.pypa.io/get-pip.py
RUN 	   python get-pip.py
RUN        pip install -U pip setuptools
ADD        . /opt/PYHANDLE

WORKDIR    /opt/PYHANDLE

RUN python setup.py install

# TODO: Fix this Dockerfile.
