# vim:set ft=dockerfile:
FROM       centos:6

RUN        yum -y update && yum clean all && yum -y install \
           python-setuptools

ADD        . /opt/PYHANDLE

WORKDIR    /opt/PYHANDLE

RUN python setup.py install
