# vim:set ft=dockerfile:
FROM       python:3.10

RUN        pip install \
           pytest \
           pytest-cov \
           pip install -U "requests==2.23.0" && \
           pip install -U pymysql

ADD        . /opt/PYHANDLE
RUN        cd /opt/PYHANDLE && \
           python setup.py install

WORKDIR    /opt/PYHANDLE/pyhandle/tests

CMD ["./docker-entrypoint-310.sh", "coverage"]
