# vim:set ft=dockerfile:
FROM       eudat-pyhandle:py3.5

# To build base image:
#cd ../../
#docker build -t eudat-pyhandle:py3.5 -f Dockerfile-py3.5 .

# To build this:
#cd pyhandle/tests
#docker build -t temp:py3.5 -f Dockerfile-py3.5 .

# It builds successfully, but fails to run:
#docker run -it temp:py3.5


RUN        pip3 install \
           mock \
           coverage \
           nose

VOLUME     /opt/PYHANDLE/pyhandle/tests

WORKDIR    /opt/PYHANDLE/pyhandle/tests

COPY       docker-entrypoint.sh ./

ENTRYPOINT ["./docker-entrypoint.sh"]

CMD        ["coverage"]

# TODO: Fix this Dockerfile.
# TODO: Document usage of this Dockerfile.


