# vim:set ft=dockerfile:
FROM       python:3.10

RUN        useradd jenkins 

RUN        pip install \
           mock \
           pytest \
           pytest-cov \
           pip install -U "requests==2.23.0" && \
           pip install -U pymysql \
           pip install -U sphinx

ADD        . /opt/PYHANDLE
RUN        cd /opt/PYHANDLE && \
           python setup.py install

WORKDIR    /opt/PYHANDLE/pyhandle/tests

CMD ["./docker-entrypoint-310.sh", "coverage"]
