# vim:set ft=dockerfile:
FROM       python:3.6

RUN        pip install \
           mock \
           coverage \
           nose 

ADD        . /opt/PYHANDLE
RUN        cd /opt/PYHANDLE && \
           python setup.py install

WORKDIR    /opt/PYHANDLE/pyhandle/tests

CMD ["./docker-entrypoint.sh", "coverage"]
